version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/examples/es6"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/examples/react"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/examples/react-select"
    schedule:
      interval: "weekly"
